### ISSUE TITLE
请问gif和MP4互转的样例吗

### ISSUE THREAD

**Issue by Hellozhongxin** [jarlen/PhotoEdit#11]
请问gif和MP4互转的样例吗

**Comment by jarlen** [comment]
@Hellozhongxin  在另外一个项目里面，有个NativeFFmpeg类,有相关方法和说明，暂时没有sample

**Comment by Hellozhongxin** [comment]
好的，找到了，正好手头要做一个项目，需要大量用到这样的转换和合成，感谢您的分享！

**Comment by Hellozhongxin** [comment]
您好，您的 那个项目so文件只有arm架构，请问这样可以兼容市面上所有的主流机型吗？
